[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
via_ir = true
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
xrplevm_testnet = "https://rpc.testnet.xrplevm.org"
arc_testnet = "https://rpc.testnet.arc.network"
